# Generated by Django 6.1 on 2026-08-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='Landing', max_length=100)),
                ('framework', models.CharField(default='React', max_length=100)),
                ('price', models.CharField(default='Free', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('exports', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('preview_image', models.URLField(blank=True, default='', max_length=500)),
                ('uploaded_file', models.FileField(blank=True, default='', upload_to='designs/previews/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('url', 'URL')], default='url', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
