# Generated by Django 5.2.7 on 2026-08-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='css_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='design',
            name='html_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='design',
            name='js_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
