# Generated by Django 5.2.7 on 2026-08-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs_app', '0002_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='generated_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
