# Generated by Django 5.2.7 on 2026-08-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs_app', '0003_design_generated_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='generated_code',
        ),
    ]
