# Generated by Django 5.2.7 on 2026-09-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs_app', '0003_category_contactmessage_adminauditlog_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='astro_code',
            field=models.TextField(blank=True, default='', help_text='Astro component code'),
        ),
        migrations.AddField(
            model_name='design',
            name='gallery_image_1',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='design',
            name='gallery_image_2',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='design',
            name='gallery_image_3',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='design',
            name='gallery_image_4',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='design',
            name='gallery_image_5',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='design',
            name='prompt',
            field=models.TextField(blank=True, default='', help_text='AI prompt used to generate this design'),
        ),
        migrations.AddField(
            model_name='design',
            name='react_code',
            field=models.TextField(blank=True, default='', help_text='React component code'),
        ),
        migrations.AddField(
            model_name='design',
            name='svelte_code',
            field=models.TextField(blank=True, default='', help_text='Svelte component code'),
        ),
        migrations.AddField(
            model_name='design',
            name='vue_code',
            field=models.TextField(blank=True, default='', help_text='Vue component code'),
        ),
    ]
