# Generated by Django 5.2.7 on 2026-08-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs_app', '0004_remove_design_generated_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
