# Generated by Django 5.2.7 on 2026-09-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs_app', '0004_design_astro_code_design_gallery_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='next_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='design',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='design',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='design',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('design_view', 'Design View'), ('design_export', 'Design Export'), ('design_download', 'Design Download'), ('search', 'Search'), ('signup', 'Sign Up'), ('login', 'Login'), ('review', 'Review')], max_length=30),
        ),
        migrations.AlterField(
            model_name='design',
            name='astro_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='design',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='design',
            name='react_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='design',
            name='svelte_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='design',
            name='vue_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='DesignRemix',
        ),
    ]
