# Generated by Django 5.2.7 on 2026-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs_app', '0005_design_next_code_design_published_design_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('one-time', 'One Time')], default='month', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=list)),
                ('design_limit', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
    ]
