# Generated by Django 5.2.7 on 2026-09-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs_app', '0006_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='accessibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='design',
            name='animations',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='design',
            name='browser_support',
            field=models.CharField(blank=True, default='Chrome, Firefox, Safari, Edge', max_length=200),
        ),
        migrations.AddField(
            model_name='design',
            name='colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='design',
            name='creator',
            field=models.CharField(blank=True, default='ZanDev', max_length=100),
        ),
        migrations.AddField(
            model_name='design',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='design',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='design',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='design',
            name='layout_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='design',
            name='license',
            field=models.CharField(default='MIT', max_length=50),
        ),
        migrations.AddField(
            model_name='design',
            name='pricing',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='design',
            name='responsive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='design',
            name='style',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='design',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='design',
            name='typography',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
