import { memo } from 'react';
import TiltCard from './cards/TiltCard';
import FlipCard from './cards/FlipCard';
import FloatCard from './cards/FloatCard';
import TerminalCard from './cards/TerminalCard';
import CodeEditorCard from './cards/CodeEditorCard';
import MetricCard from './cards/MetricCard';
import ProgressCard from './cards/ProgressCard';
import StatCard from './cards/StatCard';
import PolaroidCard from './cards/PolaroidCard';
import BentoCard from './cards/BentoCard';
import MatrixCard from './cards/MatrixCard';
import ParticleCard from './cards/ParticleCard';
import HoloCard from './cards/HoloCard';
import GlassCard from './cards/GlassCard';
import GradientCard from './cards/GradientCard';
import BaseCard from './cards/BaseCard';

const CARD_MAP = {
  TiltCard,
  FlipCard,
  FloatCard,
  TerminalCard,
  CodeEditorCard,
  MetricCard,
  ProgressCard,
  StatCard,
  PolaroidCard,
  BentoCard,
  MatrixCard,
  ParticleCard,
  HoloCard,
  GlassCard,
  GradientCard,
  BaseCard,
  // Aliases for styles referencing components not yet split into separate files
  CubeCard: TiltCard,
  MagneticCard: FloatCard,
  ZoomCard: FloatCard,
  ExpandCard: FloatCard,
  GlowCard: HoloCard,
  RippleCard: FloatCard,
  DragCard: FloatCard,
  BlueprintCard: TerminalCard,
  GlitchCard: MatrixCard,
  ASCIICard: TerminalCard,
  DebugCard: TerminalCard,
  MinimapCard: CodeEditorCard,
  DiffCard: CodeEditorCard,
  SSHCard: TerminalCard,
  CompileCard: TerminalCard,
  KPICard: MetricCard,
  TableCard: StatCard,
  BarChartCard: MetricCard,
  CalendarCard: StatCard,
  TimelineCard: StatCard,
  HeatmapCard: ProgressCard,
  PieCard: ProgressCard,
  GaugeCard: ProgressCard,
  SparklineCard: MetricCard,
  RadarCard: ProgressCard,
  StackedBarCard: ProgressCard,
  FunnelCard: ProgressCard,
  WaveCard: ParticleCard,
  ScanlineCard: MatrixCard,
  NoiseCard: MatrixCard,
  CRTCard: TerminalCard,
  VHSCard: MatrixCard,
  PulseCard: HoloCard,
  ShimmerCard: GlassCard,
  LavaCard: ParticleCard,
  AuroraCard: HoloCard,
  StarfieldCard: ParticleCard,
  SmokeCard: ParticleCard,
  FireCard: ParticleCard,
  ElectricCard: ParticleCard,
  CyberCard: HoloCard,
  OrganicCard: GlassCard,
  RetroCard: TerminalCard,
  LuxuryCard: GradientCard,
  NeonCard: HoloCard,
  SteampunkCard: TerminalCard,
  VaporCard: HoloCard,
  BrutalistCard: BaseCard,
  NordicCard: GlassCard,
  ZenCard: BaseCard,
  SpaceCard: HoloCard,
  UnderwaterCard: GlassCard,
  DesertCard: GradientCard,
  ForestCard: GradientCard,
  MasonryCard: BentoCard,
  StackedCard: BentoCard,
  SplitCard: BentoCard,
  OverlapCard: BentoCard,
  SidebarCard: BentoCard,
  MagazineCard: BaseCard,
  PosterCard: BaseCard,
  LabelCard: BaseCard,
  NewspaperCard: BaseCard,
  TypewriterCard: BaseCard,
  IndexCard: BaseCard,
  BizCard: BaseCard,
  PostcardCard: BaseCard,
  PuzzleCard: BaseCard,
  CircuitCard: MatrixCard,
  NotebookCard: BaseCard,
  DashboardCard: MetricCard,
  WidgetCard: StatCard,
  NotifCard: BaseCard,
  ChatCard: BaseCard,
  RecipeCard: BaseCard,
  TicketCard: BaseCard,
  BadgeCard: BaseCard,
  AccordionCard: BaseCard,
  TabCard: BaseCard,
  TooltipCard: BaseCard,
  SerifCard: BaseCard,
  MonoCard: TerminalCard,
  DisplayCard: BaseCard,
  ScriptCard: BaseCard,
  GeoCard: BaseCard,
  StencilCard: BaseCard,
  HandwrittenCard: BaseCard,
  PixelCard: MatrixCard,
  OutlineCard: BaseCard,
  GradientTextCard: GradientCard,
  DropCapCard: BaseCard,
  InlineCodeCard: CodeEditorCard,
  TagCloudCard: BaseCard,
  QuoteCard: BaseCard,
  HighlightCard: BaseCard,
  MaterialCard: BaseCard,
  NeumorphCard: BaseCard,
  GlassMorphCard: GlassCard,
  ClayCard: BaseCard,
  FloatingCard: FloatCard,
  EmbossedCard: BaseCard,
  DebossedCard: BaseCard,
  LayeredCard: BaseCard,
  ShadowStackCard: BaseCard,
  PaperCard: BaseCard,
  FabricCard: BaseCard,
  MetalCard: BaseCard,
  WoodCard: BaseCard,
  StoneCard: BaseCard,
  FrostedCard: GlassCard,
};

function ToolCard({ tool, style, onExport, index }) {
  const Component = CARD_MAP[style.component] || BaseCard;
  return <Component tool={tool} style={style} onExport={onExport} index={index} />;
}

export default memo(ToolCard);
