"""
Comprehensive seed script for 100 unique designs.
Each design has unique title, description, images, pricing, and metadata.
"""
import os
import sys
import json
import django
import random

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'zda.settings')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
django.setup()

from designs_app.models import Design

# 100 unique design definitions
DESIGNS = [
    # ===== TECH & SaaS (1-10) =====
    {
        "name": "Nebula Analytics",
        "category": "SaaS",
        "style": "Futuristic",
        "industry": "Technology",
        "description": "A constellation-inspired analytics dashboard that transforms raw data into celestial visualizations. Designed for data teams who want to explore metrics through an immersive dark interface with glowing data points and orbital navigation patterns.",
        "framework": "React",
        "price": "$49",
        "tags": ["dashboard", "analytics", "dark", "futuristic", "data-viz"],
        "colors": {"primary": "#6366f1", "secondary": "#8b5cf6", "accent": "#22d3ee", "bg": "#0f0f23", "surface": "#1a1a2e", "text": "#e2e8f0"},
        "typography": {"heading": "Space Grotesk", "body": "Inter"},
        "animations": "fade",
        "layout": "dashboard",
        "difficulty": "advanced"
    },
    {
        "name": "Quantum Cloud",
        "category": "Technology",
        "style": "Minimal",
        "industry": "Cloud Computing",
        "description": "Clean cloud infrastructure management panel with zero-gravity floating cards. Uses depth perception through subtle shadows and glass morphism to create an ethereal yet functional workspace for DevOps teams managing distributed systems.",
        "framework": "React",
        "price": "$39",
        "tags": ["cloud", "minimal", "glass", "infrastructure", "devops"],
        "colors": {"primary": "#3b82f6", "secondary": "#60a5fa", "accent": "#34d399", "bg": "#ffffff", "surface": "#f8fafc", "text": "#1e293b"},
        "typography": {"heading": "Plus Jakarta Sans", "body": "Inter"},
        "animations": "slide",
        "layout": "dashboard",
        "difficulty": "intermediate"
    },
    {
        "name": "CryptoVault Exchange",
        "category": "Finance",
        "style": "Dark Premium",
        "industry": "Cryptocurrency",
        "description": "Professional cryptocurrency trading platform with real-time price tickers, portfolio allocation wheels, and candlestick chart overlays. Built for active traders who need instant access to market data with zero visual clutter.",
        "framework": "React",
        "price": "$79",
        "tags": ["crypto", "trading", "dark", "finance", "charts"],
        "colors": {"primary": "#f59e0b", "secondary": "#10b981", "accent": "#ef4444", "bg": "#0c0c14", "surface": "#16162a", "text": "#f1f5f9"},
        "typography": {"heading": "JetBrains Mono", "body": "Inter"},
        "animations": "glow",
        "layout": "dashboard",
        "difficulty": "advanced"
    },
    {
        "name": "Synapse AI Studio",
        "category": "Technology",
        "style": "Cyberpunk",
        "industry": "Artificial Intelligence",
        "description": "Neural network visualization platform for machine learning engineers. Features flowing data pipelines, model architecture diagrams, and training progress monitors wrapped in a neon-lit cyberpunk aesthetic.",
        "framework": "React",
        "price": "$59",
        "tags": ["ai", "machine-learning", "cyberpunk", "neural", "tech"],
        "colors": {"primary": "#a855f7", "secondary": "#ec4899", "accent": "#06b6d4", "bg": "#0a0a0f", "surface": "#141420", "text": "#e4e4e7"},
        "typography": {"heading": "Orbitron", "body": "Space Grotesk"},
        "animations": "pulse",
        "layout": "dashboard",
        "difficulty": "advanced"
    },
    {
        "name": "DevForge IDE",
        "category": "Technology",
        "style": "Monochrome",
        "industry": "Software Development",
        "description": "Browser-based development environment with terminal integration, file tree navigation, and collaborative editing. Stripped-down monochrome interface eliminates distractions while maintaining full IDE capabilities.",
        "framework": "React",
        "price": "$45",
        "tags": ["ide", "developer", "monospace", "coding", "minimal"],
        "colors": {"primary": "#a1a1aa", "secondary": "#71717a", "accent": "#4ade80", "bg": "#18181b", "surface": "#27272a", "text": "#fafafa"},
        "typography": {"heading": "IBM Plex Mono", "body": "IBM Plex Sans"},
        "animations": "none",
        "layout": "editor",
        "difficulty": "advanced"
    },
    {
        "name": "FlowState Project Hub",
        "category": "SaaS",
        "style": "Soft UI",
        "industry": "Productivity",
        "description": "Kanban-style project management with soft neumorphic cards, smooth drag animations, and contextual task relationships. Designed for teams who prefer tactile, physical-feeling interfaces over flat design.",
        "framework": "React",
        "price": "$35",
        "tags": ["project-management", "kanban", "neumorphism", "productivity"],
        "colors": {"primary": "#818cf8", "secondary": "#a78bfa", "accent": "#f472b6", "bg": "#e8e8ef", "surface": "#d4d4de", "text": "#3f3f46"},
        "typography": {"heading": "Nunito", "body": "Nunito Sans"},
        "animations": "spring",
        "layout": "kanban",
        "difficulty": "intermediate"
    },
    {
        "name": "Apex CRM",
        "category": "SaaS",
        "style": "Corporate",
        "industry": "Sales",
        "description": "Enterprise customer relationship management with pipeline visualization, contact enrichment cards, and revenue forecasting graphs. Professional blue-toned interface built for sales teams managing complex deal cycles.",
        "framework": "React",
        "price": "$69",
        "tags": ["crm", "sales", "enterprise", "pipeline", "business"],
        "colors": {"primary": "#2563eb", "secondary": "#3b82f6", "accent": "#10b981", "bg": "#f8fafc", "surface": "#ffffff", "text": "#1e293b"},
        "typography": {"heading": "Plus Jakarta Sans", "body": "Inter"},
        "animations": "slide",
        "layout": "dashboard",
        "difficulty": "advanced"
    },
    {
        "name": "Pulse Monitoring",
        "category": "Technology",
        "style": "Futuristic",
        "industry": "DevOps",
        "description": "Real-time server monitoring dashboard with heartbeat animations, anomaly detection highlights, and incident timeline. Dark interface with bioluminescent green accents that pulse with system health status.",
        "framework": "React",
        "price": "$55",
        "tags": ["monitoring", "devops", "real-time", "alerts", "infrastructure"],
        "colors": {"primary": "#22c55e", "secondary": "#16a34a", "accent": "#ef4444", "bg": "#09090b", "surface": "#18181b", "text": "#d4d4d8"},
        "typography": {"heading": "JetBrains Mono", "body": "Inter"},
        "animations": "pulse",
        "layout": "dashboard",
        "difficulty": "advanced"
    },
    {
        "name": "Nexus API Gateway",
        "category": "Technology",
        "style": "Minimal",
        "industry": "API Management",
        "description": "API documentation and gateway management console with live endpoint testing, rate limit visualizers, and usage analytics. Clean white interface with monospaced code blocks and minimal chrome.",
        "framework": "React",
        "price": "$42",
        "tags": ["api", "documentation", "minimal", "gateway", "developer"],
        "colors": {"primary": "#6366f1", "secondary": "#818cf8", "accent": "#f59e0b", "bg": "#ffffff", "surface": "#fafafa", "text": "#27272a"},
        "typography": {"heading": "Space Grotesk", "body": "Inter"},
        "animations": "fade",
        "layout": "documentation",
        "difficulty": "intermediate"
    },
    {
        "name": "Meridian SaaS Billing",
        "category": "Finance",
        "style": "Clean",
        "industry": "SaaS",
        "description": "Subscription billing and revenue analytics with MRR charts, churn indicators, and customer lifetime value dashboards. Minimal interface focused on financial clarity for SaaS founders.",
        "framework": "React",
        "price": "$38",
        "tags": ["billing", "saas", "revenue", "subscription", "finance"],
        "colors": {"primary": "#0ea5e9", "secondary": "#38bdf8", "accent": "#8b5cf6", "bg": "#ffffff", "surface": "#f0f9ff", "text": "#0c4a6e"},
        "typography": {"heading": "DM Sans", "body": "Inter"},
        "animations": "slide",
        "layout": "dashboard",
        "difficulty": "intermediate"
    },

    # ===== E-COMMERCE (11-20) =====
    {
        "name": "Velvet Atelier",
        "category": "E-commerce",
        "style": "Luxury",
        "industry": "Fashion",
        "description": "High-end fashion e-commerce with editorial product photography, silk-smooth scroll transitions, and velvet-textured UI elements. Premium black and gold palette designed for luxury brand storefronts.",
        "framework": "React",
        "price": "$89",
        "tags": ["fashion", "luxury", "ecommerce", "editorial", "premium"],
        "colors": {"primary": "#d4a574", "secondary": "#b8860b", "accent": "#f5f5dc", "bg": "#0a0a0a", "surface": "#1a1a1a", "text": "#fafafa"},
        "typography": {"heading": "Bodoni Moda", "body": "Cormorant Garamond"},
        "animations": "reveal",
        "layout": "ecommerce",
        "difficulty": "advanced"
    },
    {
        "name": "Terra Organics Market",
        "category": "E-commerce",
        "style": "Organic",
        "industry": "Food & Beverage",
        "description": "Farm-to-table organic grocery marketplace with produce freshness indicators, seasonal recommendation engines, and recipe-linked shopping. Warm earth tones with hand-drawn botanical illustrations.",
        "framework": "React",
        "price": "$45",
        "tags": ["organic", "grocery", "sustainable", "food", "marketplace"],
        "colors": {"primary": "#65a30d", "secondary": "#84cc16", "accent": "#ea580c", "bg": "#fefce8", "surface": "#fef9c3", "text": "#365314"},
        "typography": {"heading": "Playfair Display", "body": "Source Serif 4"},
        "animations": "fade",
        "layout": "ecommerce",
        "difficulty": "intermediate"
    },
    {
        "name": "Circuit Electronics",
        "category": "E-commerce",
        "style": "Tech",
        "industry": "Electronics",
        "description": "Component-level electronics marketplace with parametric search, compatibility checkers, and datasheet previews. Circuit board green accent lines on dark surfaces for an authentic hardware aesthetic.",
        "framework": "React",
        "price": "$55",
        "tags": ["electronics", "components", "hardware", "technical", "marketplace"],
        "colors": {"primary": "#16a34a", "secondary": "#22c55e", "accent": "#eab308", "bg": "#111827", "surface": "#1f2937", "text": "#e5e7eb"},
        "typography": {"heading": "JetBrains Mono", "body": "Inter"},
        "animations": "glitch",
        "layout": "ecommerce",
        "difficulty": "advanced"
    },
    {
        "name": "Lumiere Jewelry",
        "category": "E-commerce",
        "style": "Luxury",
        "industry": "Jewelry",
        "description": "Fine jewelry e-commerce with 360-degree product viewers, gemstone certification badges, and appointment booking. Crystal-clear white surfaces with champagne gold accents radiating understated elegance.",
        "framework": "React",
        "price": "$95",
        "tags": ["jewelry", "luxury", "premium", "elegant", "fine-goods"],
        "colors": {"primary": "#c9a96e", "secondary": "#daa520", "accent": "#f5f5f5", "bg": "#fafaf9", "surface": "#ffffff", "text": "#1c1917"},
        "typography": {"heading": "Cormorant Garamond", "body": "Lora"},
        "animations": "shimmer",
        "layout": "ecommerce",
        "difficulty": "advanced"
    },
    {
        "name": "Nomad Gear Co",
        "category": "E-commerce",
        "style": "Adventure",
        "industry": "Outdoor",
        "description": "Outdoor adventure gear store with trail condition integrations, gear comparison matrices, and expedition packing lists. Rugged texture backgrounds with compass-rose navigation motifs.",
        "framework": "React",
        "price": "$52",
        "tags": ["outdoor", "adventure", "gear", "camping", "hiking"],
        "colors": {"primary": "#b45309", "secondary": "#d97706", "accent": "#059669", "bg": "#fef3c7", "surface": "#fffbeb", "text": "#451a03"},
        "typography": {"heading": "Montserrat", "body": "Open Sans"},
        "animations": "slide",
        "layout": "ecommerce",
        "difficulty": "intermediate"
    },
    {
        "name": "Pantry Chef Box",
        "category": "E-commerce",
        "style": "Playful",
        "industry": "Food Delivery",
        "description": "Meal kit subscription service with recipe previews, nutritional breakdowns, and weekly menu planners. Warm kitchen-inspired color palette with hand-lettered accents and food photography focus.",
        "framework": "React",
        "price": "$35",
        "tags": ["meal-kit", "subscription", "food", "cooking", "recipes"],
        "colors": {"primary": "#dc2626", "secondary": "#f97316", "accent": "#16a34a", "bg": "#fff7ed", "surface": "#ffffff", "text": "#1c1917"},
        "typography": {"heading": "Fredoka", "body": "Nunito"},
        "animations": "bounce",
        "layout": "ecommerce",
        "difficulty": "beginner"
    },
    {
        "name": "Atelier Footwear",
        "category": "E-commerce",
        "style": "Editorial",
        "industry": "Fashion",
        "description": "Premium sneaker and footwear store with size-guided AR try-on, release countdown timers, and brand story pages. Magazine-style layouts with oversized product photography.",
        "framework": "React",
        "price": "$62",
        "tags": ["sneakers", "footwear", "fashion", "streetwear", "release"],
        "colors": {"primary": "#18181b", "secondary": "#27272a", "accent": "#f97316", "bg": "#ffffff", "surface": "#fafafa", "text": "#09090b"},
        "typography": {"heading": "Bebas Neue", "body": "Inter"},
        "animations": "parallax",
        "layout": "ecommerce",
        "difficulty": "advanced"
    },
    {
        "name": "Serenity Home",
        "category": "E-commerce",
        "style": "Scandinavian",
        "industry": "Home Decor",
        "description": "Nordic-inspired home furnishings marketplace with room scene configurators, material swatch viewers, and interior design mood boards. Warm whites with natural wood textures and muted sage accents.",
        "framework": "React",
        "price": "$48",
        "tags": ["furniture", "scandinavian", "home", "interior", "nordic"],
        "colors": {"primary": "#a3a3a3", "secondary": "#d4d4d4", "accent": "#84a98c", "bg": "#fafaf9", "surface": "#f5f5f4", "text": "#1c1917"},
        "typography": {"heading": "Jost", "body": "Inter"},
        "animations": "fade",
        "layout": "ecommerce",
        "difficulty": "intermediate"
    },
    {
        "name": "Vinyl Records Co",
        "category": "E-commerce",
        "style": "Retro",
        "industry": "Music",
        "description": "Vinyl record marketplace with album art galleries, turntable preview animations, and genre-based discovery shelves. Warm analog tones with groove-pattern backgrounds and vintage label typography.",
        "framework": "React",
        "price": "$42",
        "tags": ["vinyl", "music", "records", "retro", "analog"],
        "colors": {"primary": "#b91c1c", "secondary": "#fbbf24", "accent": "#1e40af", "bg": "#1c1917", "surface": "#292524", "text": "#e7e5e4"},
        "typography": {"heading": "Righteous", "body": "Barlow"},
        "animations": "spin",
        "layout": "ecommerce",
        "difficulty": "intermediate"
    },
    {
        "name": "Artisan Candle Studio",
        "category": "E-commerce",
        "style": "Soft",
        "industry": "Home & Fragrance",
        "description": "Handcrafted candle boutique with scent layer visualization, burn-time calculators, and mood-based recommendations. Warm amber palette with wax-drip decorative elements and soft glow effects.",
        "framework": "React",
        "price": "$32",
        "tags": ["candles", "handmade", "fragrance", "artisan", "home"],
        "colors": {"primary": "#d97706", "secondary": "#f59e0b", "accent": "#92400e", "bg": "#fffbeb", "surface": "#fef3c7", "text": "#451a03"},
        "typography": {"heading": "Cormorant", "body": "Lora"},
        "animations": "glow",
        "layout": "ecommerce",
        "difficulty": "beginner"
    },

    # ===== TRAVEL & HOSPITALITY (21-30) =====
    {
        "name": "Azure Bay Resort",
        "category": "Travel",
        "style": "Tropical",
        "industry": "Hospitality",
        "description": "Luxury tropical resort booking platform with immersive destination galleries, beach condition widgets, and activity scheduling. Ocean-blue gradients meeting warm sand tones for an instant vacation atmosphere.",
        "framework": "React",
        "price": "$72",
        "tags": ["resort", "tropical", "booking", "luxury", "beach"],
        "colors": {"primary": "#0284c7", "secondary": "#06b6d4", "accent": "#f59e0b", "bg": "#f0f9ff", "surface": "#e0f2fe", "text": "#0c4a6e"},
        "typography": {"heading": "Playfair Display", "body": "Source Sans 3"},
        "animations": "wave",
        "layout": "landing",
        "difficulty": "advanced"
    },
    {
        "name": "Summit Expeditions",
        "category": "Travel",
        "style": "Adventure",
        "industry": "Tourism",
        "description": "Mountain adventure tour operator with elevation profile visualizations, weather condition dashboards, and gear checklists. Rugged outdoor palette with topographic map textures and compass navigation.",
        "framework": "React",
        "price": "$58",
        "tags": ["adventure", "mountain", "expedition", "hiking", "outdoor"],
        "colors": {"primary": "#1d4ed8", "secondary": "#60a5fa", "accent": "#22c55e", "bg": "#f8fafc", "surface": "#e2e8f0", "text": "#0f172a"},
        "typography": {"heading": "Montserrat", "body": "Inter"},
        "animations": "parallax",
        "layout": "landing",
        "difficulty": "advanced"
    },
    {
        "name": "Metropolis City Guide",
        "category": "Travel",
        "style": "Urban",
        "industry": "Tourism",
        "description": "City exploration platform with interactive neighborhood maps, curated walking routes, and local venue recommendations. Geometric grid layouts with transit-line-inspired navigation patterns.",
        "framework": "React",
        "price": "$42",
        "tags": ["city", "urban", "guide", "exploration", "local"],
        "colors": {"primary": "#6366f1", "secondary": "#818cf8", "accent": "#f43f5e", "bg": "#ffffff", "surface": "#f8fafc", "text": "#1e293b"},
        "typography": {"heading": "Space Grotesk", "body": "Inter"},
        "animations": "slide",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "Oceana Cruises",
        "category": "Travel",
        "style": "Elegant",
        "industry": "Cruise",
        "description": "Luxury cruise line booking with deck plan explorers, itinerary timelines, and cabin comparison tools. Deep navy palette with gold trim and wave-pattern decorative borders throughout.",
        "framework": "React",
        "price": "$85",
        "tags": ["cruise", "luxury", "ocean", "voyage", "booking"],
        "colors": {"primary": "#1e3a5f", "secondary": "#c9a96e", "accent": "#f5f5dc", "bg": "#0f172a", "surface": "#1e293b", "text": "#e2e8f0"},
        "typography": {"heading": "Cormorant Garamond", "body": "Lato"},
        "animations": "float",
        "layout": "landing",
        "difficulty": "advanced"
    },
    {
        "name": "Safari Trails",
        "category": "Travel",
        "style": "Natural",
        "industry": "Wildlife Tourism",
        "description": "African safari booking platform with wildlife sighting calendars, lodge comparison matrices, and conservation impact reports. Warm savanna palette with animal silhouette accents and earthy textures.",
        "framework": "React",
        "price": "$68",
        "tags": ["safari", "wildlife", "africa", "nature", "conservation"],
        "colors": {"primary": "#b45309", "secondary": "#92400e", "accent": "#15803d", "bg": "#fefce8", "surface": "#fef9c3", "text": "#422006"},
        "typography": {"heading": "Playfair Display", "body": "Source Serif 4"},
        "animations": "fade",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "Ryokan Japan",
        "category": "Travel",
        "style": "Japanese Minimal",
        "industry": "Hospitality",
        "description": "Traditional Japanese inn booking with tatami room tours, onsen availability calendars, and cultural experience scheduling. Zen-inspired whitespace with ink wash textures and bamboo accents.",
        "framework": "React",
        "price": "$78",
        "tags": ["japan", "ryokan", "traditional", "zen", "minimal"],
        "colors": {"primary": "#1c1917", "secondary": "#57534e", "accent": "#dc2626", "bg": "#fafaf9", "surface": "#f5f5f4", "text": "#1c1917"},
        "typography": {"heading": "Noto Serif JP", "body": "Inter"},
        "animations": "fade",
        "layout": "landing",
        "difficulty": "advanced"
    },
    {
        "name": "Alpine Chalets",
        "category": "Travel",
        "style": "Rustic",
        "industry": "Mountain Tourism",
        "description": "Mountain ski resort and chalet booking with slope condition dashboards, snow forecast widgets, and après-ski event calendars. Warm wood textures with fresh snow-white backgrounds and mountain silhouettes.",
        "framework": "React",
        "price": "$62",
        "tags": ["ski", "alpine", "chalet", "winter", "mountain"],
        "colors": {"primary": "#1d4ed8", "secondary": "#3b82f6", "accent": "#ef4444", "bg": "#f0f9ff", "surface": "#dbeafe", "text": "#1e3a5f"},
        "typography": {"heading": "Poppins", "body": "Inter"},
        "animations": "snow",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "Bali Bliss Retreats",
        "category": "Travel",
        "style": "Bohemian",
        "industry": "Wellness Tourism",
        "description": "Bali wellness retreat bookings with yoga class schedules, meditation session timers, and spa treatment menus. Warm terracotta palette with tropical leaf patterns and mandala decorative elements.",
        "framework": "React",
        "price": "$55",
        "tags": ["bali", "wellness", "retreat", "yoga", "meditation"],
        "colors": {"primary": "#c2410c", "secondary": "#ea580c", "accent": "#16a34a", "bg": "#fff7ed", "surface": "#ffedd5", "text": "#431407"},
        "typography": {"heading": "Cormorant Garamond", "body": "Quicksand"},
        "animations": "float",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "Nordic Fjords",
        "category": "Travel",
        "style": "Scandinavian",
        "industry": "Nature Tourism",
        "description": "Norwegian fjord exploration with boat tour bookings, aurora borealis forecasts, and cabin accommodation selectors. Cool blue-grey palette with aurora-gradient accents and clean Nordic typography.",
        "framework": "React",
        "price": "$58",
        "tags": ["norway", "fjord", "aurora", "nordic", "nature"],
        "colors": {"primary": "#1e40af", "secondary": "#3b82f6", "accent": "#22d3ee", "bg": "#eff6ff", "surface": "#dbeafe", "text": "#1e3a5f"},
        "typography": {"heading": "Jost", "body": "Inter"},
        "animations": "aurora",
        "layout": "landing",
        "difficulty": "advanced"
    },
    {
        "name": "Havana Nights",
        "category": "Travel",
        "style": "Retro",
        "industry": "Cultural Tourism",
        "description": "Cuba cultural tourism platform with vintage car tour bookings, salsa event calendars, and colonial architecture walking routes. Vibrant Caribbean palette with retro sign typography and textured paper backgrounds.",
        "framework": "React",
        "price": "$45",
        "tags": ["cuba", "havana", "cultural", "retro", "vintage"],
        "colors": {"primary": "#dc2626", "secondary": "#f59e0b", "accent": "#0ea5e9", "bg": "#fefce8", "surface": "#fef9c3", "text": "#451a03"},
        "typography": {"heading": "Righteous", "body": "Barlow"},
        "animations": "slide",
        "layout": "landing",
        "difficulty": "intermediate"
    },

    # ===== RESTAURANT & FOOD (31-40) =====
    {
        "name": "Ember Steakhouse",
        "category": "Restaurant",
        "style": "Dark Premium",
        "industry": "Fine Dining",
        "description": "Premium steakhouse website with meat aging timelines, sommelier wine pairing suggestions, and private dining room bookings. Dark leather-inspired palette with ember-glow accents and smoky overlay effects.",
        "framework": "React",
        "price": "$65",
        "tags": ["steakhouse", "fine-dining", "premium", "dark", "restaurant"],
        "colors": {"primary": "#991b1b", "secondary": "#b91c1c", "accent": "#f59e0b", "bg": "#1c1917", "surface": "#292524", "text": "#e7e5e4"},
        "typography": {"heading": "Bodoni Moda", "body": "Lora"},
        "animations": "reveal",
        "layout": "landing",
        "difficulty": "advanced"
    },
    {
        "name": "Bloom Plant Kitchen",
        "category": "Restaurant",
        "style": "Fresh",
        "industry": "Vegan Dining",
        "description": "Plant-based restaurant with seasonal menu rotations, ingredient sourcing stories, and garden-to-table philosophy pages. Fresh green palette with botanical illustrations and compostable packaging callouts.",
        "framework": "React",
        "price": "$38",
        "tags": ["vegan", "plant-based", "sustainable", "fresh", "restaurant"],
        "colors": {"primary": "#15803d", "secondary": "#22c55e", "accent": "#eab308", "bg": "#f0fdf4", "surface": "#dcfce7", "text": "#14532d"},
        "typography": {"heading": "Josefin Sans", "body": "Nunito"},
        "animations": "grow",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "Kawa Sushi Bar",
        "category": "Restaurant",
        "style": "Japanese Minimal",
        "industry": "Japanese Cuisine",
        "description": "Authentic sushi bar website with omakase course visualizations, sake pairing guides, and chef biography features. Clean white surfaces with red accent circles and minimal ink-brush decorative elements.",
        "framework": "React",
        "price": "$52",
        "tags": ["sushi", "japanese", "omakase", "minimal", "fine-dining"],
        "colors": {"primary": "#1c1917", "secondary": "#dc2626", "accent": "#f5f5f5", "bg": "#fafaf9", "surface": "#ffffff", "text": "#1c1917"},
        "typography": {"heading": "Noto Sans JP", "body": "Inter"},
        "animations": "fade",
        "layout": "landing",
        "difficulty": "advanced"
    },
    {
        "name": "Crust Artisan Bakery",
        "category": "Restaurant",
        "style": "Warm",
        "industry": "Bakery",
        "description": "Artisan bakery with bread-making process timelines, daily fresh-bake schedules, and wholesale ordering. Warm golden palette with flour-dust texture overlays and handwritten label typography.",
        "framework": "React",
        "price": "$32",
        "tags": ["bakery", "artisan", "bread", "fresh", "handmade"],
        "colors": {"primary": "#b45309", "secondary": "#d97706", "accent": "#7c2d12", "bg": "#fffbeb", "surface": "#fef3c7", "text": "#451a03"},
        "typography": {"heading": "Pacifico", "body": "Quicksand"},
        "animations": "float",
        "layout": "landing",
        "difficulty": "beginner"
    },
    {
        "name": "Napoli Pizzeria",
        "category": "Restaurant",
        "style": "Rustic Italian",
        "industry": "Italian Cuisine",
        "description": "Authentic Neapolitan pizzeria with wood-fired oven showcase, topping customization builders, and family story pages. Warm red and cream palette with hand-painted tile patterns and rustic textures.",
        "framework": "React",
        "price": "$35",
        "tags": ["pizza", "italian", "napoli", "wood-fired", "traditional"],
        "colors": {"primary": "#dc2626", "secondary": "#15803d", "accent": "#f59e0b", "bg": "#fefce8", "surface": "#fef9c3", "text": "#451a03"},
        "typography": {"heading": "Abril Fatface", "body": "Lora"},
        "animations": "bounce",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "Chai & Chatter",
        "category": "Restaurant",
        "style": "Cozy",
        "industry": "Cafe",
        "description": "Cozy cafe chain with live seat availability, barista specialty showcases, and community event boards. Warm brown palette with steam-rising animations and comfortable rounded typography.",
        "framework": "React",
        "price": "$28",
        "tags": ["cafe", "coffee", "cozy", "community", "warm"],
        "colors": {"primary": "#78350f", "secondary": "#92400e", "accent": "#fbbf24", "bg": "#fefce8", "surface": "#fef9c3", "text": "#451a03"},
        "typography": {"heading": "Quicksand", "body": "Nunito"},
        "animations": "steam",
        "layout": "landing",
        "difficulty": "beginner"
    },
    {
        "name": "Spice Route Kitchen",
        "category": "Restaurant",
        "style": "Vibrant",
        "industry": "Indian Cuisine",
        "description": "Modern Indian restaurant with spice-level customization, thali composition builders, and festival menu previews. Vibrant spice-market palette with mandala patterns and gold leaf accents.",
        "framework": "React",
        "price": "$42",
        "tags": ["indian", "spice", "curry", "vibrant", "authentic"],
        "colors": {"primary": "#ea580c", "secondary": "#dc2626", "accent": "#eab308", "bg": "#fff7ed", "surface": "#ffedd5", "text": "#431407"},
        "typography": {"heading": "Playfair Display", "body": "Source Sans 3"},
        "animations": "spice",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "Salt & Tide",
        "category": "Restaurant",
        "style": "Coastal",
        "industry": "Seafood",
        "description": "Coastal seafood restaurant with daily catch displays, sustainability scorecards, and tide-synchronized specials. Ocean-blue palette with rope textures and driftwood-inspired UI elements.",
        "framework": "React",
        "price": "$55",
        "tags": ["seafood", "coastal", "sustainable", "fresh", "ocean"],
        "colors": {"primary": "#0369a1", "secondary": "#0284c7", "accent": "#f59e0b", "bg": "#f0f9ff", "surface": "#e0f2fe", "text": "#0c4a6e"},
        "typography": {"heading": "DM Serif Display", "body": "Inter"},
        "animations": "wave",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "Seoul Street",
        "category": "Restaurant",
        "style": "Neon",
        "industry": "Korean Cuisine",
        "description": "Korean street food concept with neon-lit menu boards, K-pop culture integrations, and group ordering. Vibrant neon palette on dark backgrounds with Hangul typography accents and street photography.",
        "framework": "React",
        "price": "$38",
        "tags": ["korean", "street-food", "neon", "seoul", "vibrant"],
        "colors": {"primary": "#ec4899", "secondary": "#8b5cf6", "accent": "#06b6d4", "bg": "#0a0a0f", "surface": "#18181b", "text": "#e4e4e7"},
        "typography": {"heading": "Bebas Neue", "body": "Inter"},
        "animations": "neon",
        "layout": "landing",
        "difficulty": "advanced"
    },
    {
        "name": "Harvest Table",
        "category": "Restaurant",
        "style": "Farm-to-Table",
        "industry": "American Cuisine",
        "description": "Farm-to-table restaurant with seasonal ingredient spotlights, farmer partnership profiles, and harvest calendar. Warm wood and green palette with hand-drawn produce illustrations and rustic signage.",
        "framework": "React",
        "price": "$48",
        "tags": ["farm-to-table", "seasonal", "local", "organic", "american"],
        "colors": {"primary": "#166534", "secondary": "#15803d", "accent": "#b45309", "bg": "#f0fdf4", "surface": "#dcfce7", "text": "#14532d"},
        "typography": {"heading": "Libre Baskerville", "body": "Nunito"},
        "animations": "grow",
        "layout": "landing",
        "difficulty": "intermediate"
    },

    # ===== REAL ESTATE (41-50) =====
    {
        "name": "Prestige Estates",
        "category": "Real Estate",
        "style": "Luxury",
        "industry": "Real Estate",
        "description": "Luxury real estate agency with virtual property tours, neighborhood wealth indicators, and agent performance dashboards. Black and gold palette with marble texture accents and premium serif typography.",
        "framework": "React",
        "price": "$88",
        "tags": ["luxury", "real-estate", "premium", "property", "high-end"],
        "colors": {"primary": "#1c1917", "secondary": "#c9a96e", "accent": "#f5f5f5", "bg": "#0a0a0a", "surface": "#1a1a1a", "text": "#fafafa"},
        "typography": {"heading": "Cormorant Garamond", "body": "Inter"},
        "animations": "reveal",
        "layout": "listing",
        "difficulty": "advanced"
    },
    {
        "name": "Skyline Penthouses",
        "category": "Real Estate",
        "style": "Modern",
        "industry": "Urban Real Estate",
        "description": "High-rise penthouse listings with 360-degree skyline views, building amenity maps, and mortgage calculator widgets. Glass-and-steel palette with panoramic photo galleries and vertical scroll narratives.",
        "framework": "React",
        "price": "$75",
        "tags": ["penthouse", "skyline", "urban", "luxury", "high-rise"],
        "colors": {"primary": "#0ea5e9", "secondary": "#38bdf8", "accent": "#f59e0b", "bg": "#f0f9ff", "surface": "#e0f2fe", "text": "#0c4a6e"},
        "typography": {"heading": "Plus Jakarta Sans", "body": "Inter"},
        "animations": "parallax",
        "layout": "listing",
        "difficulty": "advanced"
    },
    {
        "name": "Coastal Living Realty",
        "category": "Real Estate",
        "style": "Beach",
        "industry": "Coastal Real Estate",
        "description": "Beachfront property marketplace with tide charts, coastal erosion data, and waterfront amenity scoring. Sandy beige palette with ocean-blue wave accents and shell-pattern decorative elements.",
        "framework": "React",
        "price": "$62",
        "tags": ["beach", "coastal", "waterfront", "property", "ocean"],
        "colors": {"primary": "#0284c7", "secondary": "#06b6d4", "accent": "#f59e0b", "bg": "#f0f9ff", "surface": "#e0f2fe", "text": "#0c4a6e"},
        "typography": {"heading": "Josefin Sans", "body": "Nunito Sans"},
        "animations": "wave",
        "layout": "listing",
        "difficulty": "intermediate"
    },
    {
        "name": "Mountain Haven Cabins",
        "category": "Real Estate",
        "style": "Rustic",
        "industry": "Mountain Real Estate",
        "description": "Mountain cabin and lodge real estate with trail access maps, ski proximity indicators, and wilderness area boundaries. Warm wood palette with pine-tree silhouette accents and compass navigation.",
        "framework": "React",
        "price": "$55",
        "tags": ["cabin", "mountain", "rustic", "lodge", "wilderness"],
        "colors": {"primary": "#78350f", "secondary": "#92400e", "accent": "#166534", "bg": "#fefce8", "surface": "#fef9c3", "text": "#451a03"},
        "typography": {"heading": "Montserrat", "body": "Open Sans"},
        "animations": "parallax",
        "layout": "listing",
        "difficulty": "intermediate"
    },
    {
        "name": "Urban Loft District",
        "category": "Real Estate",
        "style": "Industrial",
        "industry": "Urban Real Estate",
        "description": "Converted warehouse and loft property listings with floor plan configurators, neighborhood walkability scores, and transit access maps. Exposed brick palette with steel-blue accents and industrial typography.",
        "framework": "React",
        "price": "$58",
        "tags": ["loft", "industrial", "urban", "warehouse", "converted"],
        "colors": {"primary": "#57534e", "secondary": "#78716c", "accent": "#2563eb", "bg": "#fafaf9", "surface": "#e7e5e4", "text": "#1c1917"},
        "typography": {"heading": "Oswald", "body": "Inter"},
        "animations": "slide",
        "layout": "listing",
        "difficulty": "intermediate"
    },
    {
        "name": "Vineyard Estates",
        "category": "Real Estate",
        "style": "Elegant",
        "industry": "Wine Country",
        "description": "Wine country property listings with vineyard acreage calculators, harvest season calendars, and winery proximity maps. Purple grape-inspired palette with Tuscan textures and vintage labels.",
        "framework": "React",
        "price": "$72",
        "tags": ["vineyard", "wine-country", "elegant", "tuscan", "estate"],
        "colors": {"primary": "#7e22ce", "secondary": "#a855f7", "accent": "#b45309", "bg": "#faf5ff", "surface": "#f3e8ff", "text": "#581c87"},
        "typography": {"heading": "Playfair Display", "body": "Lora"},
        "animations": "fade",
        "layout": "listing",
        "difficulty": "advanced"
    },
    {
        "name": "Smart Home Living",
        "category": "Real Estate",
        "style": "Futuristic",
        "industry": "Smart Homes",
        "description": "Smart home-enabled property listings with IoT device previews, energy efficiency ratings, and automation capability scores. Tech-forward palette with circuit-board patterns and glowing interfaces.",
        "framework": "React",
        "price": "$68",
        "tags": ["smart-home", "iot", "futuristic", "technology", "automated"],
        "colors": {"primary": "#6366f1", "secondary": "#818cf8", "accent": "#06b6d4", "bg": "#0f0f23", "surface": "#1a1a2e", "text": "#e2e8f0"},
        "typography": {"heading": "Space Grotesk", "body": "Inter"},
        "animations": "glow",
        "layout": "listing",
        "difficulty": "advanced"
    },
    {
        "name": "Heritage Homes",
        "category": "Real Estate",
        "style": "Classic",
        "industry": "Historic Properties",
        "description": "Historic property listings with architectural period guides, restoration cost estimators, and heritage registry information. Warm cream palette with period-appropriate typography and ornamental borders.",
        "framework": "React",
        "price": "$58",
        "tags": ["historic", "heritage", "classic", "period", "restoration"],
        "colors": {"primary": "#78350f", "secondary": "#92400e", "accent": "#166534", "bg": "#fefce8", "surface": "#fef9c3", "text": "#451a03"},
        "typography": {"heading": "Cormorant Garamond", "body": "Crimson Text"},
        "animations": "reveal",
        "layout": "listing",
        "difficulty": "intermediate"
    },
    {
        "name": "Suburban Family Homes",
        "category": "Real Estate",
        "style": "Friendly",
        "industry": "Residential",
        "description": "Family-oriented suburban home listings with school district ratings, park proximity maps, and family-friendly amenity filters. Warm approachable palette with rounded corners and friendly illustrations.",
        "framework": "React",
        "price": "$42",
        "tags": ["suburban", "family", "residential", "schools", "community"],
        "colors": {"primary": "#2563eb", "secondary": "#3b82f6", "accent": "#16a34a", "bg": "#eff6ff", "surface": "#dbeafe", "text": "#1e3a5f"},
        "typography": {"heading": "Nunito", "body": "Nunito Sans"},
        "animations": "bounce",
        "layout": "listing",
        "difficulty": "beginner"
    },
    {
        "name": "Tiny House Village",
        "category": "Real Estate",
        "style": "Minimal",
        "industry": "Alternative Housing",
        "description": "Tiny house community marketplace with space optimization visualizers, sustainability calculators, and community rule comparisons. Natural palette with wood-grain textures and minimalist leaf icons.",
        "framework": "React",
        "price": "$35",
        "tags": ["tiny-house", "minimal", "sustainable", "alternative", "community"],
        "colors": {"primary": "#166534", "secondary": "#22c55e", "accent": "#b45309", "bg": "#f0fdf4", "surface": "#dcfce7", "text": "#14532d"},
        "typography": {"heading": "DM Sans", "body": "Inter"},
        "animations": "fade",
        "layout": "listing",
        "difficulty": "beginner"
    },

    # ===== PORTFOLIO & CREATIVE (51-60) =====
    {
        "name": "Prism Photography",
        "category": "Portfolio",
        "style": "Editorial",
        "industry": "Photography",
        "description": "Photography portfolio with lightbox galleries, EXIF data displays, and booking calendars. Clean white canvas with dramatic image cropping and magazine-style grid layouts.",
        "framework": "React",
        "price": "$45",
        "tags": ["photography", "portfolio", "editorial", "gallery", "creative"],
        "colors": {"primary": "#18181b", "secondary": "#27272a", "accent": "#f97316", "bg": "#ffffff", "surface": "#fafafa", "text": "#09090b"},
        "typography": {"heading": "Bebas Neue", "body": "Inter"},
        "animations": "lightbox",
        "layout": "portfolio",
        "difficulty": "advanced"
    },
    {
        "name": "Chromatic Studio",
        "category": "Portfolio",
        "style": "Bold",
        "industry": "Design Agency",
        "description": "Multi-disciplinary design studio portfolio with case study deep-dives, team member spotlights, and client logo walls. High-contrast palette with oversized typography and dramatic color blocking.",
        "framework": "React",
        "price": "$58",
        "tags": ["agency", "design", "portfolio", "bold", "creative"],
        "colors": {"primary": "#f43f5e", "secondary": "#ec4899", "accent": "#06b6d4", "bg": "#0a0a0f", "surface": "#18181b", "text": "#fafafa"},
        "typography": {"heading": "Clash Display", "body": "Inter"},
        "animations": "split",
        "layout": "portfolio",
        "difficulty": "advanced"
    },
    {
        "name": "Archiform Architects",
        "category": "Portfolio",
        "style": "Architectural",
        "industry": "Architecture",
        "description": "Architecture firm portfolio with project timeline visualizations, material palette showcases, and 3D model embeds. Concrete and glass palette with blueprint-grid backgrounds and structural typography.",
        "framework": "React",
        "price": "$62",
        "tags": ["architecture", "portfolio", "minimal", "professional", "design"],
        "colors": {"primary": "#57534e", "secondary": "#a8a29e", "accent": "#0ea5e9", "bg": "#fafaf9", "surface": "#e7e5e4", "text": "#1c1917"},
        "typography": {"heading": "Archivo", "body": "Inter"},
        "animations": "reveal",
        "layout": "portfolio",
        "difficulty": "advanced"
    },
    {
        "name": "Melody Wave Music",
        "category": "Portfolio",
        "style": "Dynamic",
        "industry": "Music",
        "description": "Musician portfolio with embedded audio players, concert tour visualizers, and merchandise store integrations. Sound-wave-inspired animations with dark palette and neon frequency accents.",
        "framework": "React",
        "price": "$48",
        "tags": ["music", "portfolio", "audio", "dynamic", "artist"],
        "colors": {"primary": "#8b5cf6", "secondary": "#a78bfa", "accent": "#f43f5e", "bg": "#0a0a0f", "surface": "#18181b", "text": "#e4e4e7"},
        "typography": {"heading": "Orbitron", "body": "Inter"},
        "animations": "waveform",
        "layout": "portfolio",
        "difficulty": "advanced"
    },
    {
        "name": "Reel Cinematics",
        "category": "Portfolio",
        "style": "Cinematic",
        "industry": "Film Production",
        "description": "Film production company portfolio with showreel lightboxes, project breakdowns, and crew profiles. Dark cinema palette with film-strip decorative elements and letterbox framing.",
        "framework": "React",
        "price": "$55",
        "tags": ["film", "cinema", "production", "video", "portfolio"],
        "colors": {"primary": "#1c1917", "secondary": "#44403c", "accent": "#f59e0b", "bg": "#0a0a0a", "surface": "#1a1a1a", "text": "#fafafa"},
        "typography": {"heading": "Bebas Neue", "body": "Barlow"},
        "animations": "reel",
        "layout": "portfolio",
        "difficulty": "advanced"
    },
    {
        "name": "Ink & Pixel Studio",
        "category": "Portfolio",
        "style": "Playful",
        "industry": "Illustration",
        "description": "Illustrator portfolio with zoomable artwork galleries, process breakdowns, and client commission forms. Colorful hand-drawn aesthetic with sketch-paper textures and marker-style typography.",
        "framework": "React",
        "price": "$38",
        "tags": ["illustration", "art", "portfolio", "playful", "creative"],
        "colors": {"primary": "#ec4899", "secondary": "#8b5cf6", "accent": "#22c55e", "bg": "#fdf4ff", "surface": "#fae8ff", "text": "#701a75"},
        "typography": {"heading": "Fredoka", "body": "Quicksand"},
        "animations": "draw",
        "layout": "portfolio",
        "difficulty": "intermediate"
    },
    {
        "name": "Motion Canvas",
        "category": "Portfolio",
        "style": "Kinetic",
        "industry": "Motion Design",
        "description": "Motion designer portfolio with video background heroes, animation showcases, and interactive demo embeds. Dark palette with gradient trails and timecode-stamped project cards.",
        "framework": "React",
        "price": "$52",
        "tags": ["motion", "animation", "video", "portfolio", "kinetic"],
        "colors": {"primary": "#06b6d4", "secondary": "#22d3ee", "accent": "#f43f5e", "bg": "#0a0a0f", "surface": "#18181b", "text": "#e4e4e7"},
        "typography": {"heading": "Space Grotesk", "body": "Inter"},
        "animations": "kinetic",
        "layout": "portfolio",
        "difficulty": "advanced"
    },
    {
        "name": "Brutalist Workshop",
        "category": "Portfolio",
        "style": "Brutalist",
        "industry": "Web Design",
        "description": "Web design studio portfolio in raw brutalist aesthetic. Exposed HTML structure, monospaced type, black borders on white, and deliberately unpolished interactions celebrating the web's raw nature.",
        "framework": "React",
        "price": "$42",
        "tags": ["brutalist", "raw", "web-design", "experimental", "anti-design"],
        "colors": {"primary": "#000000", "secondary": "#ffffff", "accent": "#ff0000", "bg": "#ffffff", "surface": "#f5f5f5", "text": "#000000"},
        "typography": {"heading": "Courier Prime", "body": "IBM Plex Mono"},
        "animations": "glitch",
        "layout": "portfolio",
        "difficulty": "advanced"
    },
    {
        "name": "Terra Ceramics",
        "category": "Portfolio",
        "style": "Earthy",
        "industry": "Ceramics",
        "description": "Ceramic artist portfolio with process photography, glaze recipe databases, and workshop booking. Warm clay palette with textured backgrounds and hand-thrown typography curves.",
        "framework": "React",
        "price": "$35",
        "tags": ["ceramics", "pottery", "handmade", "art", "earthy"],
        "colors": {"primary": "#92400e", "secondary": "#b45309", "accent": "#166534", "bg": "#fefce8", "surface": "#fef9c3", "text": "#451a03"},
        "typography": {"heading": "Libre Baskerville", "body": "Crimson Text"},
        "animations": "spin",
        "layout": "portfolio",
        "difficulty": "beginner"
    },
    {
        "name": "Neon Nights Collective",
        "category": "Portfolio",
        "style": "Cyberpunk",
        "industry": "Digital Art",
        "description": "Digital art collective portfolio with immersive 3D galleries, WebGL transitions, and NFT minting integrations. Cyberpunk palette with scan-line effects and holographic UI elements.",
        "framework": "React",
        "price": "$65",
        "tags": ["digital-art", "cyberpunk", "nft", "3d", "collective"],
        "colors": {"primary": "#d946ef", "secondary": "#f43f5e", "accent": "#06b6d4", "bg": "#0a0a0f", "surface": "#141420", "text": "#e4e4e7"},
        "typography": {"heading": "Orbitron", "body": "Space Grotesk"},
        "animations": "hologram",
        "layout": "portfolio",
        "difficulty": "advanced"
    },

    # ===== EDUCATION (61-70) =====
    {
        "name": "Zenith Academy",
        "category": "Education",
        "style": "Clean",
        "industry": "Online Learning",
        "description": "Online learning platform with progress tracking visualizations, peer discussion forums, and certificate generators. Clean blue-and-white palette with achievement badge systems and streak counters.",
        "framework": "React",
        "price": "$48",
        "tags": ["education", "online-learning", "courses", "clean", "platform"],
        "colors": {"primary": "#2563eb", "secondary": "#3b82f6", "accent": "#16a34a", "bg": "#eff6ff", "surface": "#dbeafe", "text": "#1e3a5f"},
        "typography": {"heading": "Plus Jakarta Sans", "body": "Inter"},
        "animations": "slide",
        "layout": "dashboard",
        "difficulty": "intermediate"
    },
    {
        "name": "Lingua Connect",
        "category": "Education",
        "style": "Friendly",
        "industry": "Language Learning",
        "description": "Language learning platform with speech recognition previews, flashcard Spaced repetition systems, and native speaker matching. Playful palette with speech-bubble UI elements and flag icons.",
        "framework": "React",
        "price": "$38",
        "tags": ["language", "learning", "multilingual", "education", "speaking"],
        "colors": {"primary": "#8b5cf6", "secondary": "#a78bfa", "accent": "#f59e0b", "bg": "#faf5ff", "surface": "#f3e8ff", "text": "#581c87"},
        "typography": {"heading": "Nunito", "body": "Nunito Sans"},
        "animations": "bounce",
        "layout": "dashboard",
        "difficulty": "intermediate"
    },
    {
        "name": "CodeCraft Academy",
        "category": "Education",
        "style": "Tech",
        "industry": "Coding Education",
        "description": "Coding bootcamp platform with live code editors, project submission pipelines, and mentor matching. Dark IDE-inspired palette with terminal-green accents and monospaced challenge cards.",
        "framework": "React",
        "price": "$55",
        "tags": ["coding", "bootcamp", "programming", "developer", "education"],
        "colors": {"primary": "#22c55e", "secondary": "#16a34a", "accent": "#6366f1", "bg": "#0f172a", "surface": "#1e293b", "text": "#e2e8f0"},
        "typography": {"heading": "JetBrains Mono", "body": "Inter"},
        "animations": "typewriter",
        "layout": "dashboard",
        "difficulty": "advanced"
    },
    {
        "name": "Harmony Music School",
        "category": "Education",
        "style": "Elegant",
        "industry": "Music Education",
        "description": "Music education platform with instrument progress trackers, practice session timers, and recital scheduling. Warm palette with sheet music textures and treble clef decorative elements.",
        "framework": "React",
        "price": "$42",
        "tags": ["music", "education", "instrument", "lessons", "practice"],
        "colors": {"primary": "#1c1917", "secondary": "#78350f", "accent": "#dc2626", "bg": "#fafaf9", "surface": "#f5f5f4", "text": "#1c1917"},
        "typography": {"heading": "Playfair Display", "body": "Lora"},
        "animations": "music",
        "layout": "dashboard",
        "difficulty": "intermediate"
    },
    {
        "name": "Atelier Art School",
        "category": "Education",
        "style": "Creative",
        "industry": "Art Education",
        "description": "Art school platform with digital canvas integrations, portfolio review systems, and supply wishlists. Colorful palette with paint-splatter textures and brush-stroke UI accents.",
        "framework": "React",
        "price": "$45",
        "tags": ["art", "education", "painting", "creative", "studio"],
        "colors": {"primary": "#ec4899", "secondary": "#f43f5e", "accent": "#3b82f6", "bg": "#fdf4ff", "surface": "#fce7f3", "text": "#831843"},
        "typography": {"heading": "Fredoka", "body": "Nunito"},
        "animations": "paint",
        "layout": "dashboard",
        "difficulty": "intermediate"
    },
    {
        "name": "FinanceU",
        "category": "Education",
        "style": "Professional",
        "industry": "Financial Education",
        "description": "Financial literacy platform with interactive budget simulators, investment calculators, and certification exam preps. Professional navy palette with chart-based lesson previews and progress bars.",
        "framework": "React",
        "price": "$52",
        "tags": ["finance", "education", "investment", "professional", "certification"],
        "colors": {"primary": "#1e40af", "secondary": "#2563eb", "accent": "#16a34a", "bg": "#eff6ff", "surface": "#dbeafe", "text": "#1e3a5f"},
        "typography": {"heading": "Plus Jakarta Sans", "body": "Inter"},
        "animations": "slide",
        "layout": "dashboard",
        "difficulty": "intermediate"
    },
    {
        "name": "Science Lab Academy",
        "category": "Education",
        "style": "Modern",
        "industry": "Science Education",
        "description": "Virtual science lab platform with experiment simulations, molecular structure viewers, and lab report templates. Clean palette with molecule-pattern accents and periodic table color coding.",
        "framework": "React",
        "price": "$58",
        "tags": ["science", "lab", "experiment", "chemistry", "education"],
        "colors": {"primary": "#0ea5e9", "secondary": "#06b6d4", "accent": "#f59e0b", "bg": "#f0f9ff", "surface": "#e0f2fe", "text": "#0c4a6e"},
        "typography": {"heading": "Space Grotesk", "body": "Inter"},
        "animations": "molecule",
        "layout": "dashboard",
        "difficulty": "advanced"
    },
    {
        "name": "Junior Coders Club",
        "category": "Education",
        "style": "Playful",
        "industry": "Kids Education",
        "description": "Children coding education with block-based programming previews, achievement trees, and parent dashboards. Bright playful palette with character mascots and game-like progression systems.",
        "framework": "React",
        "price": "$32",
        "tags": ["kids", "coding", "education", "playful", "children"],
        "colors": {"primary": "#f97316", "secondary": "#eab308", "accent": "#22c55e", "bg": "#fff7ed", "surface": "#ffedd5", "text": "#7c2d12"},
        "typography": {"heading": "Baloo 2", "body": "Nunito"},
        "animations": "bounce",
        "layout": "dashboard",
        "difficulty": "beginner"
    },
    {
        "name": "Mindful Academy",
        "category": "Education",
        "style": "Calm",
        "industry": "Wellness Education",
        "description": "Mindfulness and meditation education platform with session timers, mood tracking journals, and guided meditation libraries. Soft gradient palette with breathing animation accents and zen circles.",
        "framework": "React",
        "price": "$35",
        "tags": ["mindfulness", "meditation", "wellness", "calm", "education"],
        "colors": {"primary": "#6366f1", "secondary": "#818cf8", "accent": "#22d3ee", "bg": "#eef2ff", "surface": "#e0e7ff", "text": "#3730a3"},
        "typography": {"heading": "Jost", "body": "Inter"},
        "animations": "breathe",
        "layout": "dashboard",
        "difficulty": "beginner"
    },
    {
        "name": "Global Studies Institute",
        "category": "Education",
        "style": "Academic",
        "industry": "Higher Education",
        "description": "University department website with course catalog browsers, faculty research profiles, and academic calendar integrations. Traditional academic palette with crests, seals, and serif typography.",
        "framework": "React",
        "price": "$48",
        "tags": ["university", "academic", "research", "faculty", "courses"],
        "colors": {"primary": "#7c2d12", "secondary": "#991b1b", "accent": "#b45309", "bg": "#fefce8", "surface": "#fef9c3", "text": "#451a03"},
        "typography": {"heading": "Cormorant Garamond", "body": "Crimson Text"},
        "animations": "fade",
        "layout": "landing",
        "difficulty": "intermediate"
    },

    # ===== HEALTH & FITNESS (71-80) =====
    {
        "name": "Iron Forge Gym",
        "category": "Health",
        "style": "Bold",
        "industry": "Fitness",
        "description": "Gym and fitness center website with class scheduling, trainer profiles, and membership tier comparisons. High-energy palette with bold geometric shapes and motivational typography.",
        "framework": "React",
        "price": "$42",
        "tags": ["gym", "fitness", "training", "workout", "health"],
        "colors": {"primary": "#dc2626", "secondary": "#ef4444", "accent": "#f59e0b", "bg": "#0a0a0a", "surface": "#1a1a1a", "text": "#fafafa"},
        "typography": {"heading": "Oswald", "body": "Inter"},
        "animations": "power",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "Serenity Yoga Studio",
        "category": "Health",
        "style": "Peaceful",
        "industry": "Yoga",
        "description": "Yoga studio with class level indicators, instructor philosophy pages, and meditation timer integrations. Soft gradient palette with lotus flower accents and breathing rhythm animations.",
        "framework": "React",
        "price": "$38",
        "tags": ["yoga", "meditation", "wellness", "peaceful", "studio"],
        "colors": {"primary": "#8b5cf6", "secondary": "#a78bfa", "accent": "#f472b6", "bg": "#faf5ff", "surface": "#f3e8ff", "text": "#581c87"},
        "typography": {"heading": "Cormorant Garamond", "body": "Quicksand"},
        "animations": "breathe",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "MedCore Clinic",
        "category": "Health",
        "style": "Clean",
        "industry": "Healthcare",
        "description": "Medical clinic website with appointment booking, doctor specialty directories, and patient portal previews. Clinical white palette with trust-building blue accents and clear information hierarchy.",
        "framework": "React",
        "price": "$65",
        "tags": ["medical", "clinic", "healthcare", "doctor", "appointment"],
        "colors": {"primary": "#0284c7", "secondary": "#0ea5e9", "accent": "#16a34a", "bg": "#f0f9ff", "surface": "#e0f2fe", "text": "#0c4a6e"},
        "typography": {"heading": "Plus Jakarta Sans", "body": "Inter"},
        "animations": "fade",
        "layout": "landing",
        "difficulty": "advanced"
    },
    {
        "name": "Oasis Spa Retreat",
        "category": "Health",
        "style": "Luxury",
        "industry": "Spa & Wellness",
        "description": "Luxury spa and wellness retreat with treatment menus, therapist profiles, and availability calendars. Warm gold and cream palette with water-ripple effects and botanical leaf accents.",
        "framework": "React",
        "price": "$72",
        "tags": ["spa", "wellness", "luxury", "retreat", "massage"],
        "colors": {"primary": "#c9a96e", "secondary": "#d4a574", "accent": "#166534", "bg": "#fefce8", "surface": "#fef9c3", "text": "#451a03"},
        "typography": {"heading": "Cormorant Garamond", "body": "Lora"},
        "animations": "float",
        "layout": "landing",
        "difficulty": "advanced"
    },
    {
        "name": "NutriTrack App",
        "category": "Health",
        "style": "Fresh",
        "industry": "Nutrition",
        "description": "Nutrition tracking app with macro visualization wheels, meal photo journals, and recipe recommendation engines. Fresh green palette with food-group color coding and appetite-appealing layouts.",
        "framework": "React",
        "price": "$32",
        "tags": ["nutrition", "diet", "health", "tracking", "meal"],
        "colors": {"primary": "#16a34a", "secondary": "#22c55e", "accent": "#f97316", "bg": "#f0fdf4", "surface": "#dcfce7", "text": "#14532d"},
        "typography": {"heading": "DM Sans", "body": "Inter"},
        "animations": "ring",
        "layout": "dashboard",
        "difficulty": "intermediate"
    },
    {
        "name": "Pulse Fitness Tracker",
        "category": "Health",
        "style": "Tech",
        "industry": "Fitness Tech",
        "description": "Wearable fitness tracker dashboard with heart rate zone visualizations, sleep analysis charts, and activity streak calendars. Dark tech palette with neon accent lines and data-rich cards.",
        "framework": "React",
        "price": "$45",
        "tags": ["fitness", "tracker", "wearable", "health", "data"],
        "colors": {"primary": "#06b6d4", "secondary": "#22d3ee", "accent": "#f43f5e", "bg": "#0f172a", "surface": "#1e293b", "text": "#e2e8f0"},
        "typography": {"heading": "Space Grotesk", "body": "Inter"},
        "animations": "pulse",
        "layout": "dashboard",
        "difficulty": "advanced"
    },
    {
        "name": "MindWell Therapy",
        "category": "Health",
        "style": "Gentle",
        "industry": "Mental Health",
        "description": "Therapy and mental health practice with therapist matching questionnaires, session booking, and progress journaling. Soft pastel palette with calming gradients and safe-space messaging.",
        "framework": "React",
        "price": "$55",
        "tags": ["therapy", "mental-health", "counseling", "wellness", "mindful"],
        "colors": {"primary": "#818cf8", "secondary": "#a5b4fc", "accent": "#34d399", "bg": "#eef2ff", "surface": "#e0e7ff", "text": "#3730a3"},
        "typography": {"heading": "Nunito", "body": "Nunito Sans"},
        "animations": "gentle",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "ActiveLife Sports Club",
        "category": "Health",
        "style": "Energetic",
        "industry": "Sports Club",
        "description": "Multi-sport athletic club with facility maps, team registration, and tournament brackets. High-energy palette with motion-inspired graphics and scoreboard-style typography.",
        "framework": "React",
        "price": "$48",
        "tags": ["sports", "club", "athletic", "team", "fitness"],
        "colors": {"primary": "#dc2626", "secondary": "#f97316", "accent": "#0ea5e9", "bg": "#fef2f2", "surface": "#fee2e2", "text": "#7f1d1d"},
        "typography": {"heading": "Bebas Neue", "body": "Barlow"},
        "animations": "power",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "DentalCare Plus",
        "category": "Health",
        "style": "Friendly",
        "industry": "Dental",
        "description": "Dental practice website with smile gallery, procedure explainer animations, and insurance verification tools. Clean white palette with friendly smile icons and reassuring messaging throughout.",
        "framework": "React",
        "price": "$42",
        "tags": ["dental", "dentist", "smile", "health", "clinic"],
        "colors": {"primary": "#0ea5e9", "secondary": "#38bdf8", "accent": "#16a34a", "bg": "#f0f9ff", "surface": "#e0f2fe", "text": "#0c4a6e"},
        "typography": {"heading": "Nunito", "body": "Inter"},
        "animations": "smile",
        "layout": "landing",
        "difficulty": "beginner"
    },
    {
        "name": "VitalSigns Monitoring",
        "category": "Health",
        "style": "Clinical",
        "industry": "Medical Tech",
        "description": "Patient vital signs monitoring dashboard with real-time ECG waveforms, blood pressure trends, and medication schedules. Clinical palette with precise grid systems and medical-grade typography.",
        "framework": "React",
        "price": "$78",
        "tags": ["medical", "monitoring", "vital-signs", "clinical", "healthcare"],
        "colors": {"primary": "#0369a1", "secondary": "#0284c7", "accent": "#dc2626", "bg": "#ffffff", "surface": "#f8fafc", "text": "#0f172a"},
        "typography": {"heading": "JetBrains Mono", "body": "Inter"},
        "animations": "ecg",
        "layout": "dashboard",
        "difficulty": "advanced"
    },

    # ===== FINANCE (81-90) =====
    {
        "name": "VaultBank Digital",
        "category": "Finance",
        "style": "Trustworthy",
        "industry": "Banking",
        "description": "Digital banking dashboard with account overview cards, transaction categorization, and savings goal trackers. Professional blue palette with vault-inspired security motifs and clean data displays.",
        "framework": "React",
        "price": "$68",
        "tags": ["banking", "finance", "digital", "secure", "account"],
        "colors": {"primary": "#1e40af", "secondary": "#2563eb", "accent": "#16a34a", "bg": "#eff6ff", "surface": "#dbeafe", "text": "#1e3a5f"},
        "typography": {"heading": "Plus Jakarta Sans", "body": "Inter"},
        "animations": "slide",
        "layout": "dashboard",
        "difficulty": "advanced"
    },
    {
        "name": "Apex Investments",
        "category": "Finance",
        "style": "Premium",
        "industry": "Investment",
        "description": "Investment portfolio management with asset allocation wheels, performance attribution charts, and risk analysis dashboards. Dark premium palette with gold accent lines and sophisticated data visualizations.",
        "framework": "React",
        "price": "$82",
        "tags": ["investment", "portfolio", "wealth", "premium", "finance"],
        "colors": {"primary": "#1c1917", "secondary": "#c9a96e", "accent": "#22c55e", "bg": "#0a0a0a", "surface": "#1a1a1a", "text": "#fafafa"},
        "typography": {"heading": "Cormorant Garamond", "body": "Inter"},
        "animations": "reveal",
        "layout": "dashboard",
        "difficulty": "advanced"
    },
    {
        "name": "SafeGuard Insurance",
        "category": "Finance",
        "style": "Protective",
        "industry": "Insurance",
        "description": "Insurance platform with coverage comparison tools, claim filing wizards, and policy document viewers. Shield-inspired palette with trust-building green accents and clear coverage breakdowns.",
        "framework": "React",
        "price": "$55",
        "tags": ["insurance", "coverage", "protection", "policy", "claims"],
        "colors": {"primary": "#059669", "secondary": "#10b981", "accent": "#2563eb", "bg": "#ecfdf5", "surface": "#d1fae5", "text": "#064e3b"},
        "typography": {"heading": "DM Sans", "body": "Inter"},
        "animations": "shield",
        "layout": "landing",
        "difficulty": "intermediate"
    },
    {
        "name": "QuickBooks Lite",
        "category": "Finance",
        "style": "Functional",
        "industry": "Accounting",
        "description": "Small business accounting with invoice generators, expense categorization, and tax estimate previews. Clean functional palette with spreadsheet-inspired layouts and receipt scanning prompts.",
        "framework": "React",
        "price": "$38",
        "tags": ["accounting", "invoice", "bookkeeping", "small-business", "tax"],
        "colors": {"primary": "#059669", "secondary": "#34d399", "accent": "#6366f1", "bg": "#f0fdf4", "surface": "#dcfce7", "text": "#14532d"},
        "typography": {"heading": "Inter", "body": "Inter"},
        "animations": "none",
        "layout": "dashboard",
        "difficulty": "beginner"
    },
    {
        "name": "CrowdSpark",
        "category": "Finance",
        "style": "Community",
        "industry": "Crowdfunding",
        "description": "Crowdfunding platform with campaign progress rings, backer tier comparisons, and stretch goal trackers. Warm community palette with flame motifs and momentum-building progress animations.",
        "framework": "React",
        "price": "$52",
        "tags": ["crowdfunding", "startup", "fundraising", "community", "backers"],
        "colors": {"primary": "#ea580c", "secondary": "#f97316", "accent": "#8b5cf6", "bg": "#fff7ed", "surface": "#ffedd5", "text": "#7c2d12"},
        "typography": {"heading": "Poppins", "body": "Inter"},
        "animations": "fill",
        "layout": "listing",
        "difficulty": "intermediate"
    },
    {
        "name": "CoinBase Wallet",
        "category": "Finance",
        "style": "Modern",
        "industry": "Digital Wallet",
        "description": "Digital payment wallet with transaction history feeds, split-bill calculators, and contact payment directories. Clean modern palette with card-flip animations and biometric auth indicators.",
        "framework": "React",
        "price": "$48",
        "tags": ["wallet", "payment", "digital", "mobile", "finance"],
        "colors": {"primary": "#2563eb", "secondary": "#3b82f6", "accent": "#16a34a", "bg": "#ffffff", "surface": "#f8fafc", "text": "#1e293b"},
        "typography": {"heading": "Plus Jakarta Sans", "body": "Inter"},
        "animations": "card-flip",
        "layout": "mobile",
        "difficulty": "advanced"
    },
    {
        "name": "PennyWise Budget",
        "category": "Finance",
        "style": "Friendly",
        "industry": "Personal Finance",
        "description": "Personal budgeting app with envelope-style spending categories, bill due-date calendars, and savings challenge boards. Friendly green palette with coin animations and achievement unlocks.",
        "framework": "React",
        "price": "$28",
        "tags": ["budget", "savings", "personal-finance", "money", "tracking"],
        "colors": {"primary": "#16a34a", "secondary": "#22c55e", "accent": "#f59e0b", "bg": "#f0fdf4", "surface": "#dcfce7", "text": "#14532d"},
        "typography": {"heading": "Nunito", "body": "Nunito Sans"},
        "animations": "coin",
        "layout": "mobile",
        "difficulty": "beginner"
    },
    {
        "name": "TradeVista Pro",
        "category": "Finance",
        "style": "Professional",
        "industry": "Stock Trading",
        "description": "Professional stock trading platform with multi-chart layouts, order book visualizations, and portfolio risk analytics. Dark professional palette with Bloomberg-terminal-inspired data density.",
        "framework": "React",
        "price": "$95",
        "tags": ["trading", "stocks", "professional", "analytics", "finance"],
        "colors": {"primary": "#18181b", "secondary": "#27272a", "accent": "#22c55e", "bg": "#09090b", "surface": "#18181b", "text": "#d4d4d8"},
        "typography": {"heading": "JetBrains Mono", "body": "Inter"},
        "animations": "tick",
        "layout": "dashboard",
        "difficulty": "advanced"
    },
    {
        "name": "RealEstate Finance",
        "category": "Finance",
        "style": "Stable",
        "industry": "Mortgage",
        "description": "Mortgage and real estate finance calculator with amortization schedules, affordability estimators, and rate comparison tools. Stable earth-tone palette with house and key iconography.",
        "framework": "React",
        "price": "$45",
        "tags": ["mortgage", "real-estate", "calculator", "finance", "home-loan"],
        "colors": {"primary": "#92400e", "secondary": "#b45309", "accent": "#166534", "bg": "#fefce8", "surface": "#fef9c3", "text": "#451a03"},
        "typography": {"heading": "DM Sans", "body": "Inter"},
        "animations": "count",
        "layout": "calculator",
        "difficulty": "intermediate"
    },
    {
        "name": "CryptoYield",
        "category": "Finance",
        "style": "DeFi",
        "industry": "Decentralized Finance",
        "description": "DeFi yield farming dashboard with APY comparison tables, liquidity pool visualizers, and gas fee optimizers. Dark palette with gradient token icons and blockchain explorer patterns.",
        "framework": "React",
        "price": "$72",
        "tags": ["defi", "yield", "crypto", "blockchain", "farming"],
        "colors": {"primary": "#8b5cf6", "secondary": "#a78bfa", "accent": "#06b6d4", "bg": "#0a0a0f", "surface": "#141420", "text": "#e4e4e7"},
        "typography": {"heading": "Space Grotesk", "body": "Inter"},
        "animations": "glow",
        "layout": "dashboard",
        "difficulty": "advanced"
    },

    # ===== ENTERTAINMENT & OTHERS (91-100) =====
    {
        "name": "StreamFlix Hub",
        "category": "Entertainment",
        "style": "Cinematic",
        "industry": "Streaming",
        "description": "Video streaming platform with content carousels, watchlist management, and personalized recommendation rows. Netflix-inspired dark palette with cinematic widescreen previews and autoplay thumbnails.",
        "framework": "React",
        "price": "$58",
        "tags": ["streaming", "video", "entertainment", "movies", "shows"],
        "colors": {"primary": "#dc2626", "secondary": "#ef4444", "accent": "#f5f5f5", "bg": "#0a0a0a", "surface": "#1a1a1a", "text": "#fafafa"},
        "typography": {"heading": "Bebas Neue", "body": "Inter"},
        "animations": "parallax",
        "layout": "streaming",
        "difficulty": "advanced"
    },
    {
        "name": "Pixel Arena Gaming",
        "category": "Gaming",
        "style": "Neon",
        "industry": "Gaming",
        "description": "Gaming community platform with tournament brackets, leaderboard ladders, and game library showcases. Neon-lit dark palette with particle effects and arcade-cabinet-inspired UI frames.",
        "framework": "React",
        "price": "$52",
        "tags": ["gaming", "esports", "tournament", "community", "neon"],
        "colors": {"primary": "#d946ef", "secondary": "#f43f5e", "accent": "#06b6d4", "bg": "#0a0a0f", "surface": "#141420", "text": "#e4e4e7"},
        "typography": {"heading": "Orbitron", "body": "Space Grotesk"},
        "animations": "glitch",
        "layout": "gaming",
        "difficulty": "advanced"
    },
    {
        "name": "WaveSync Podcast",
        "category": "Entertainment",
        "style": "Audio",
        "industry": "Podcasting",
        "description": "Podcast platform with episode waveforms, playlist queues, and transcription viewers. Sound-wave-inspired dark palette with audio-reactive visual elements and chapter navigation.",
        "framework": "React",
        "price": "$38",
        "tags": ["podcast", "audio", "streaming", "episodes", "waves"],
        "colors": {"primary": "#6366f1", "secondary": "#818cf8", "accent": "#f59e0b", "bg": "#0f0f23", "surface": "#1a1a2e", "text": "#e2e8f0"},
        "typography": {"heading": "Space Grotesk", "body": "Inter"},
        "animations": "waveform",
        "layout": "audio",
        "difficulty": "intermediate"
    },
    {
        "name": "EventBlast",
        "category": "Entertainment",
        "style": "Vibrant",
        "industry": "Events",
        "description": "Event management platform with venue seating charts, ticket tier comparisons, and live schedule builders. Vibrant festival palette with confetti animations and countdown timers.",
        "framework": "React",
        "price": "$45",
        "tags": ["events", "tickets", "festival", "concert", "venue"],
        "colors": {"primary": "#f43f5e", "secondary": "#ec4899", "accent": "#8b5cf6", "bg": "#fff1f2", "surface": "#ffe4e6", "text": "#881337"},
        "typography": {"heading": "Poppins", "body": "Inter"},
        "animations": "confetti",
        "layout": "event",
        "difficulty": "intermediate"
    },
    {
        "name": "AutoPilot Motors",
        "category": "Automotive",
        "style": "Sleek",
        "industry": "Electric Vehicles",
        "description": "Electric vehicle brand showcase with 360-degree car configurators, range calculators, and charging station maps. Sleek dark palette with electric-blue accent lines and aerodynamic curve motifs.",
        "framework": "React",
        "price": "$78",
        "tags": ["ev", "electric", "automotive", "sustainable", "tech"],
        "colors": {"primary": "#0ea5e9", "secondary": "#38bdf8", "accent": "#22c55e", "bg": "#0f172a", "surface": "#1e293b", "text": "#e2e8f0"},
        "typography": {"heading": "Space Grotesk", "body": "Inter"},
        "animations": "reveal",
        "layout": "landing",
        "difficulty": "advanced"
    },
    {
        "name": "StyleVault Fashion",
        "category": "Fashion",
        "style": "Editorial",
        "industry": "Fashion",
        "description": "Fashion brand lookbook with runway video integration, collection timeline scrolls, and style-matching quizzes. High-fashion editorial palette with bold typography and full-bleed imagery.",
        "framework": "React",
        "price": "$65",
        "tags": ["fashion", "editorial", "lookbook", "style", "runway"],
        "colors": {"primary": "#09090b", "secondary": "#27272a", "accent": "#f43f5e", "bg": "#ffffff", "surface": "#fafafa", "text": "#09090b"},
        "typography": {"heading": "Bodoni Moda", "body": "Inter"},
        "animations": "parallax",
        "layout": "editorial",
        "difficulty": "advanced"
    },
    {
        "name": "Flora & Fauna",
        "category": "E-commerce",
        "style": "Botanical",
        "industry": "Plant Shop",
        "description": "Indoor plant marketplace with care requirement filters, light exposure guides, and plant parent community forums. Lush green palette with leaf-pattern backgrounds and growth-tracking features.",
        "framework": "React",
        "price": "$35",
        "tags": ["plants", "botanical", "indoor", "garden", "nature"],
        "colors": {"primary": "#166534", "secondary": "#22c55e", "accent": "#eab308", "bg": "#f0fdf4", "surface": "#dcfce7", "text": "#14532d"},
        "typography": {"heading": "Josefin Sans", "body": "Nunito"},
        "animations": "grow",
        "layout": "ecommerce",
        "difficulty": "intermediate"
    },
    {
        "name": "SnapFrame Studio",
        "category": "Creative",
        "style": "Minimal",
        "industry": "Photo Editing",
        "description": "Photo editing SaaS with before/after sliders, filter preset galleries, and batch processing queues. Ultra-clean palette with tool-panel layouts and non-destructive editing indicators.",
        "framework": "React",
        "price": "$42",
        "tags": ["photo", "editing", "filters", "creative", "saas"],
        "colors": {"primary": "#18181b", "secondary": "#3f3f46", "accent": "#f97316", "bg": "#ffffff", "surface": "#fafafa", "text": "#09090b"},
        "typography": {"heading": "Inter", "body": "Inter"},
        "animations": "slider",
        "layout": "editor",
        "difficulty": "advanced"
    },
    {
        "name": "WanderLens Travel Blog",
        "category": "Blog",
        "style": "Storytelling",
        "industry": "Travel Media",
        "description": "Travel storytelling blog with full-width photo essays, interactive route maps, and cultural context sidebars. Magazine-inspired layout with scroll-triggered narratives and ambient soundscapes.",
        "framework": "React",
        "price": "$32",
        "tags": ["travel", "blog", "storytelling", "photography", "media"],
        "colors": {"primary": "#b45309", "secondary": "#d97706", "accent": "#0ea5e9", "bg": "#fefce8", "surface": "#fef9c3", "text": "#451a03"},
        "typography": {"heading": "Playfair Display", "body": "Source Serif 4"},
        "animations": "scroll-reveal",
        "layout": "blog",
        "difficulty": "intermediate"
    },
    {
        "name": "Spectrum News",
        "category": "Magazine",
        "style": "Editorial",
        "industry": "News Media",
        "description": "Digital news magazine with categorized article grids, live update tickers, and journalist profile pages. Clean editorial palette with section dividers and accessible reading modes.",
        "framework": "React",
        "price": "$48",
        "tags": ["news", "magazine", "editorial", "articles", "media"],
        "colors": {"primary": "#1c1917", "secondary": "#44403c", "accent": "#dc2626", "bg": "#fafaf9", "surface": "#f5f5f4", "text": "#1c1917"},
        "typography": {"heading": "Merriweather", "body": "Source Serif 4"},
        "animations": "fade",
        "layout": "magazine",
        "difficulty": "intermediate"
    },
]

def create_designs():
    print("=" * 60)
    print("CREATING 100 DESIGNS")
    print("=" * 60)
    
    created = 0
    skipped = 0
    
    for idx, design_data in enumerate(DESIGNS, 1):
        name = design_data['name']
        
        # Check if design already exists
        if Design.objects.filter(name=name).exists():
            print(f"[{idx:03d}] SKIP (exists): {name}")
            skipped += 1
            continue
        
        slug = name.lower().replace(' ', '-').replace('&', 'and')
        
        # Get gallery images
        gallery_images = []
        for i in range(1, 7):
            img_path = f"/media/designs/gallery/design-{idx:03d}-{i:02d}.jpg"
            gallery_images.append(img_path)
        
        # Create design
        design = Design.objects.create(
            name=name,
            slug=slug,
            category=design_data['category'],
            framework=design_data['framework'],
            price=design_data['price'],
            score=random.randint(50, 100),
            views=random.randint(100, 5000),
            exports=random.randint(10, 500),
            description=design_data['description'],
            prompt=f"Create a {design_data['style'].lower()} {design_data['category'].lower()} website for {design_data['industry']} with {design_data['typography']['heading']} typography and {design_data['colors']['primary']} primary color.",
            preview_image=gallery_images[0] if gallery_images else '',
            gallery_image_1=gallery_images[0] if len(gallery_images) > 0 else '',
            gallery_image_2=gallery_images[1] if len(gallery_images) > 1 else '',
            gallery_image_3=gallery_images[2] if len(gallery_images) > 2 else '',
            gallery_image_4=gallery_images[3] if len(gallery_images) > 3 else '',
            gallery_image_5=gallery_images[4] if len(gallery_images) > 4 else '',
            file_type='image',
            html_code=f'<!-- {name} - {design_data["category"]} -->\n<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>{name}</title>\n<link rel="stylesheet" href="style.css">\n</head>\n<body>\n<!-- {design_data["style"]} Layout -->\n</body>\n</html>',
            css_code=f'/* {name} Styles */\n:root {{\n  --primary: {design_data["colors"]["primary"]};\n  --secondary: {design_data["colors"]["secondary"]};\n  --accent: {design_data["colors"]["accent"]};\n  --bg: {design_data["colors"]["bg"]};\n  --surface: {design_data["colors"]["surface"]};\n  --text: {design_data["colors"]["text"]};\n}}\n\n* {{ margin: 0; padding: 0; box-sizing: border-box; }}\nbody {{ font-family: \'{design_data["typography"]["body"]}\', sans-serif; background: var(--bg); color: var(--text); }}\nh1, h2, h3 {{ font-family: \'{design_data["typography"]["heading"]}\', serif; }}',
            react_code=f'import {{ useState }} from "react";\n\nexport default function {name.replace(" ", "")}() {{\n  return (\n    <div className="{slug}">\n      <h1>{name}</h1>\n      <!-- {design_data["style"]} Component -->\n    </div>\n  );\n}}',
            version=random.choice([1, 2, 3]),
            published=True,
            style=design_data['style'],
            industry=design_data['industry'],
            tags=design_data['tags'],
            colors=design_data['colors'],
            typography=design_data['typography'],
            animations=design_data['animations'],
            layout_type=design_data['layout'],
            responsive=True,
            accessibility=True,
            browser_support='Chrome, Firefox, Safari, Edge',
            license='MIT',
            difficulty=design_data['difficulty'],
            creator='ZanDev',
            pricing={
                'free': {'price': 0, 'features': ['Preview only', 'Limited access']},
                'personal': {'price': 29, 'features': ['Personal use', 'Source code', '1 project']},
                'professional': {'price': 49, 'features': ['Commercial use', 'All source code', '10 projects', 'Updates']},
                'enterprise': {'price': 99, 'features': ['Unlimited projects', 'Priority support', 'Custom modifications', 'White-label license']},
            },
            gallery_images=gallery_images,
        )
        
        print(f"[{idx:03d}] CREATED: {name} ({design_data['category']})")
        created += 1
    
    print()
    print("=" * 60)
    print(f"COMPLETE: {created} created, {skipped} skipped")
    print(f"Total designs: {Design.objects.count()}")
    print("=" * 60)

if __name__ == '__main__':
    create_designs()
